name: Lume

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: build
    # runs-on: macos-14 # Ensures we're using a macOS runner with Apple Silicon
    runs-on: cirun-test-label
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: hello
        run: pwd
      - name: cat
        run: cat .cirun.yml  
  # build2:
  #   name: build2
  #   # runs-on: macos-14 # Ensures we're using a macOS runner with Apple Silicon
  #   runs-on: foobar
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4
  # build3:
  #   name: build3
  #   # runs-on: macos-14 # Ensures we're using a macOS runner with Apple Silicon
  #   runs-on: foobar
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4             
