name: CI
on:
  push:
    branches: [ master ]
jobs:
  test-job:
    runs-on: ${{ matrix.os }}
    steps:
      - uses: mamba-org/setup-micromamba@v1
        with:
          log-level: debug
          environment-name: anndatagpu
          generate-run-shell: true
          micromamba-version: "1.3.1-0"
          create-args: >-
            python=3.10
            cupy
        env:
          ACTIONS_STEP_DEBUG: true
          CONDA: /home/runnerx/mamba
