name: CI
on:
  push:
    branches: [ master ]
jobs:
  test-job:
    runs-on: macos-13-xlarge
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4.7.0
        with:
          python-version: '3.10' 

      - name: Get Hostname
        shell: bash
        run: |
          hostname
  
      - name: Run nvidia-smi if present
        shell: bash
        run: |
          nvidia-smi || true
  
      - name: Get system Information
        shell: bash
        run: |
          uname -a
  
      - name: Get Architecture
        shell: bash
        run: |
          dpkg --print-architecture
  
      - name: Get system Disk space
        shell: bash
        run: |
          df -h
  
      - name: Get OS version
        shell: bash
        run: |
          cat /etc/*release
  
      - name: Run "lscpu"
        shell: bash
        run: lscpu      
