name: CI
on:
  push:
    branches: [ master ]
jobs:
  container-test-job:
    strategy:
      matrix:
        version: [10, 12, 14]
        os:
          - ubuntu-latest
          - macos-latest
        container_args:
          - '1'
          - ''
    runs-on: ${{ matrix.os }}
    container:
      image: node:14.16
      env:
        NODE_ENV: development
      ports:
        - 80
      volumes:
        - my_docker_volume:/volume_mount
      options: ${{ matrix.container_args }}
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
