name: blank
on:
  push:
    branches: "*"
jobs:
  linux:
    name: Linux
    runs-on: self-hosted
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: run command
        run: |
          ls
